name: DroneStabilization
channels:
  - conda-forge
  - bioconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - bzip2=1.0.8=h500dc9f_9
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - libblas=3.11.0=5_he492b99_openblas
  - libcblas=3.11.0=5_h9b27e0a_openblas
  - libcxx=21.1.8=h4fb565c_2
  - libexpat=2.7.4=h991f03e_0
  - libffi=3.4.6=h281671d_1
  - libgcc=15.2.0=h08519bb_18
  - libgfortran=15.2.0=h7e5c614_18
  - libgfortran5=15.2.0=hd16e46c_18
  - liblapack=3.11.0=5_h859234e_openblas
  - liblzma=5.8.2=h11316ed_0
  - libopenblas=0.3.30=openmp_h6006d49_4
  - libsqlite=3.51.2=hb99441e_0
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=21.1.8=h472b3d1_0
  - ncurses=6.5=h0622a9a_3
  - numpy=2.4.2=py312hb34da66_1
  - openssl=3.6.1=hb6871ef_1
  - packaging=26.0=pyhcf101f3_0
  - pandas=3.0.1=py312h8e27051_0
  - pip=26.0.1=pyh8b19718_0
  - python=3.12.10=h9ccd52b_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.12=8_cp312
  - readline=8.3=h68b038d_0
  - setuptools=82.0.0=pyh332efcf_0
  - six=1.17.0=pyhe01879c_1
  - tk=8.6.13=h7142dee_3
  - tzdata=2025c=hc9c84f9_1
  - wheel=0.46.3=pyhd8ed1ab_0
  - pip:
      - opencv-python==4.13.0.92
      - pillow==12.1.1
      - pyyaml==6.0.3
      - ruamel-yaml==0.19.1
